### ISSUE TITLE
Unsleeping laptop on develop yields blank RoomView with Unread Messages (^) status bar

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1035]
...and lots of `cannot call getTs() on null value` from minimised bundle.js - minimised code is:

`var t=_.roomReadMarkerTsMap[this.props.room.roomId];return t&&this.state.events?t<this.state.events[0].getTs()?-1:1:null}`

<img width="2030" alt="screen shot 2016-02-26 at 19 53 29" src="https://cloud.githubusercontent.com/assets/1294269/13362159/0113cf4e-dcc3-11e5-85be-ba1774f0cce3.png">

**Comment by ara4n** [comment]
...i'm seeing a variant of this on current develop, where unsleeping gives me an entirely blank room view (no 'Unread messages' bar) until I do something to make the screen re-render and then it wakes up. No JS errors.

**Comment by richvdh** [comment]
Yes, #943 has morphed into this.

**Comment by richvdh** [comment]
oh wait, this sounds slightly different to #943

**Comment by richvdh** [comment]
This has been introduced by https://github.com/matrix-org/matrix-react-sdk/pull/180. The _loadTimeline that happens when the timeline is reset now returns immediately, but the forward pagination request which it sets off (but which returns no results, because at this point there are no new events) does not. Meanwhile, the pagination requests which are spawned by the arrival of the subsequent events are ignored because there is a pagination request in play.

**Comment by richvdh** [comment]
This isn't quite fixed by https://github.com/matrix-org/matrix-react-sdk/issues/182; there is another race-condition which stops us back-paginating correctly.

**Comment by richvdh** [comment]
Now properly fixed.
