### ISSUE TITLE
Joining a room via /join results in scary 'changing room on a TimelinePanel is not supported' uncaught errors

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1036]
`TimelinePanel.js:127 Uncaught Error: changing room on a TimelinePanel is not supported`

Unsure if this is reason for panic or not.

**Comment by ara4n** [comment]
oh, it is: looks like all of React is falling over; i can't even send msgs.

**Comment by richvdh** [comment]
I'll have a look later this evening

**Comment by richvdh** [comment]
The problem here is that there are two Room objects in circulation - one which is created by the `MatrixClient.joinRoom` call and used to create the RoomView, and a second which is created by the sync loop once the room comes back down the /sync pipe.

This isn't new; what is new is the sanity check I added to `TimelinePanel` to check that you weren't changing rooms under its feet.

For now I'm going to remove the sanity check again (or rather, replace it with a warning), but I feel like that's fixing the symptom rather than the cause.
