### ISSUE TITLE
Vector UI seems broken with icons

### ISSUE THREAD

**Issue by Annwenn** [vector-im/vector-web#1043]
After having installed Vector and ran `npm run build`, the UI seems to have some quirks.
Could it be related to Nginx? (is there a particular configuration that I should follow?)
![vector-fuckup](https://cloud.githubusercontent.com/assets/8963482/13374011/38cb4aba-dd78-11e5-8f7a-8782ada98152.png)

**Comment by ara4n** [comment]
Weird - Soupbowl was reporting similar problems a few minutes ago on #vector:matrix.org and apparently solved it:

> Soupbowl
I installed the latest vector and push it with nginx. I am having 1 strange problem where the top right buttons leave room, search and the members icon do not show up, but if I go to their url img/members.svg, I can view the images. Anyone have any ideas what would cause that? Everything else works perfect
Matthew
soupbowl: weird. have you definitely flushed the whole cache?
what browser?
Soupbowl
I flushed the whole cache, tried it on edge,chrome and firefox on 3 computers
It's just strange because ever other icon works, but obviously its something I did some where, so I'll try and re install it
Matthew
can you right click on where the element should be, inspect, and see if it's in the dom?
Soupbowl
I right click and inspect the area, I see "img/members.svg", which i can input into the url bar and i can see the image
but it won't show up in vector on any of the browsers
I refreshed nginx with a fresh .conf and the problem is resolved

**Comment by ara4n** [comment]
suggest coming asking on #vector:matrix.org and see if folks can talk you through whatever's going wrong

**Comment by Annwenn** [comment]
I'm in. :)

**Comment by Annwenn** [comment]
Okay, so after some debugging, here are the results :

```
uniaika 21:53 ~ ❯❯ http HEAD http://matrix.queertoo.org/img/create-big.svg
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 1741
Content-Type: application/octet-stream
Date: Sat, 27 Feb 2016 20:55:18 GMT
ETag: "56d1a95a-6cd"
Last-Modified: Sat, 27 Feb 2016 13:49:14 GMT
Server: nginx/1.8.1
```

The interesting line here is the `application/octet-stream`. The SVG don't have the proper header, so the browser fallbacks on its default behaviour : downloading it.

This can be change in `(/usr/local)/etc/nginx/mime.types`. In my case, using a custom file, the svg line wasn't here.
I simply added `image/svg+xml                         svg svgz;` to the end of the file. and it works.

![works](https://cloud.githubusercontent.com/assets/8963482/13375413/f1e9ace6-dd9e-11e5-8c4f-c56f52c0364e.png)
