### ISSUE TITLE
Public/Private wording in Room Settings need to be improved

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1059]
Current wording (private and public with address management) is unclear on who is actually going to be able to join / see the room.

```
_**Current behaviour**_
  - A check box to switch private / public
     |_| Make this room private 
  - An "ADDRESS" section

_**Proposal for new behaviour**_
  - Add a section called "WHO CAN ACCESS THIS ROOM?"
  - Add a drop-down (or radio button but there are already a lot of radio buttons
    and it's endless to scroll the settings):

> This room is <Drop-down entry>
   <Explanation (displayed next to the drop down and updated when selection changes)

Drop-down list with associated explanation:
       - Invite-only / Only the people you've invited by email or user ID can join
       - Secret / Anyone with the room link can join
       - Public / Anyone can join and the room is listed in the directory.
         You need to set an address <link to Address section of the settings> for the room.

  - Keep the current checkbox and have it in the same section:
     |X| Let guests join this room
(Guest access should be enabled by default.)
```

**Comment by ara4n** [comment]
This has unravelled because I can't see any way to have a room joinable by the public without also publishing its alias in the room directory - so no way to implement 'secret' rooms.

Also, i suspect this would work better if guest access was included in the list of 'who can access?' options, as:

 * Invite-only
 * Secret
 * Public (no guests)
 * Public (including guests)

As it makes no sense to make an invite-only or secret room non-guest accessible - as if explicitly invited (either by an invite or sharing the link) guests should surely always be able to join.  This then kills the somewhat confusing "let guests join this room" checkbox that we can't get rid of currently.

**Comment by freelock** [comment]
How about separating these into two different sets?

## Directory status

- Public listed
- Listed for accounts on this HS
- Listed for accounts already member or with an invite
- Unlisted

## Join status

- Anyone can join, guest or registered users
- Users need an invite to join, guest or registered
- Registered users can join
- Registered users of this HS can join

For the most part I would want to have the directory only show rooms I can join -- but I can see exceptions to that, so having invite-only rooms listed publicly may be ok/desirable in some cases.

I definitely want to have secret/unlisted rooms that I can send a link to invite a guest -- e.g. Unlisted/invited guests. Or "Listed only for members/invited guests can join".

Because the current invite mechanism goes through the vector.im identity server, and guests can't connect across homeservers, for the nearer term I'd like "secret/guests can join" so I can send a link to a vector instance on our HS that can let a guest drop into the appropriate room. At the moment, though, this means making the room public and viewable in the directory for any passer-by, which is not what I want...

**Comment by ara4n** [comment]
@freelock i think this basically what the end design is doing, albeit trying to reduce the presented options to as few as possible.

Eitherway, a first cut has landed in https://github.com/matrix-org/matrix-react-sdk/pull/241 and will land once the synapse PR (https://github.com/matrix-org/synapse/pull/657) has landed :)
