### ISSUE TITLE
 Wrong date separator in case of unsent messages from yesterday

### ISSUE THREAD

**Issue by giomfo** [vector-im/vector-web#1087]
As you can see in the attached screenshot, the date separator 'Today' is displayed twice.

![screenshot](https://matrix.org/_matrix/media/v1/download/matrix.org/VDgtqGZhicUyWWTwwWXINVwk)

To reproduce:
1- Consider a room in which at least one message is unsent from yesterday (or later).
2- Send new messages in this room -> The date separator 'Today' is displayed twice (NOK)

**Comment by richvdh** [comment]
So the problem here is that we show unsent messages with a time which corresponds to when they were created and queued; however they stay at the end of the timeline. So, if you sent it yesterday, you end up with an extra date separator.

An easy fix for that, as far as it goes, would be to ignore failed messages (and local echoes in general) when considering date separators.

However, the screenshot shows another problem, which is that sometimes successfully sent messages appear *after* failed messages. Opened #1120 to track this.

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/209
