### ISSUE TITLE
Tightloop scrolling in room with ~1.5 screens worth of history

### ISSUE THREAD

**Issue by dbkr** [vector-im/vector-web#1089]
Seems to be going between a scroll event firing (ScrollPanel.js:140) and a promise done which is causing a react update (TimelinePanel.js:176). Gzipped timeline data attached.

Seems to happen as soon as I refresh the browser if it's on that room.

[TimelineRawData-20160304T111558.gz](https://github.com/vector-im/vector-web/files/158569/TimelineRawData-20160304T111558.gz)

**Comment by richvdh** [comment]
This happens when we get a response from a pagination request which contains only events we already know about. The reasons this is happening may be due to synapse bugs, but we shouldn't really tightloop in this case.

The reason we end up tightlooping is that generally we want to ignore the pagination token if the last event in a pagination request is one we already know about (because typically that means the existing pagination tokens we already have will be better bets).

The obvious workaround is to spot when we end up with a no-op from a pagination request, and always overwrite the pagination token with the new one in that situation.

**Comment by richvdh** [comment]
Looks like the majority of cases are due to https://matrix.org/jira/browse/SYN-645. But not all, and Vector's behaviour is definitely broken here.

**Comment by richvdh** [comment]
Hopefully fixed by https://github.com/matrix-org/matrix-js-sdk/issues/96
