### ISSUE TITLE
Scrollbar appears in message composer (for apparently no reason)

### ISSUE THREAD

**Issue by aviraldg** [vector-im/vector-web#1155]
![vector](https://cloud.githubusercontent.com/assets/238916/13774220/e00c1522-eac3-11e5-9405-7acb00f4e38f.png)

Check image for explanation of what I mean. This happens when the last character is deleted after a message is composed. 

Browser: Chrome Version 50.0.2661.26 unknown (64-bit)
OS: Ubuntu 15.10

**Comment by ara4n** [comment]
Matthew
Aviral Dasgupta: on https://github.com/vector-im/vector-web/issues/1155
can you try on https://vector.im/develop please?
i think that was fixed the other day

Matthew
(/beta is a week behind /develop atm)

Aviral Dasgupta
Matthew: on it
Matthew: nope, still the same :(

Matthew
wonder if it's a Chrome 50 bug

how much history does the room have? (multiple pages or less than one page?)

Aviral Dasgupta
Multiple pages
The interesting thing about this behaviour is, if I type a message and delete it, the scroll bar toggles for each character.

Matthew
yeah, i've seen this before, but i'm pretty sure we fixed it

the problem is that every time you hit delete the thing does a check to see if it needs to shrink a multi-line text input box
i guess something has changed on chrome 50 such that this triggers overflow scrollbars

* Matthew chucks this all into the bug

**Comment by ara4n** [comment]
prolly related to #1172

**Comment by ara4n** [comment]
Hopefully workedaround by https://github.com/matrix-org/matrix-react-sdk/commit/3326a50c4b8257f4a73b806d00652ef23b979458
