### ISSUE TITLE
Notification panel: Implement the notification panel as per design

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1750]
Notification panel: Implement the notification panel as per design

**Dependency**: Vector team to provide feedback and functionality in matrix.js?

* Design: small tweaks and assets marked ready

**Comment by AmandineLP** [comment]
what is the difference with #1749 ?

**Comment by ara4n** [comment]
The names of these bugs match the zeplin assets.  #1749 is just the badge on the new icon in the top right; this one is the actual panel.

Vector team will provide the actual implementation of this panel (and all the JS SDK fun and games involved) - @dbkr has this on his radar.  Visuals to be implemented however by Ribot (although in practice this should just be reusing the CSS for the main timeline perhaps).

**Comment by bradlegge** [comment]
Screen URL:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=5747295bd4eaa764278e115d

**Comment by ara4n** [comment]
There's something that doesn't feel quite right about this - perhaps because it looks too much like a normal timeline, rather than a series of unconnected mentions.  Also, the mentions should surely be mention-lozenges.  However, the visuals are the least of our problems here given the amount of plumbing work required to make it work; we can iterate later on.

**Comment by ara4n** [comment]
i did this.
