### ISSUE TITLE
General design: implement correct typography

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1753]
General design (was Chat inline link 20a screen): implement correct typography

* Design: all assets ready

**Comment by AmandineLP** [comment]
which "typography"? the font?

**Comment by ara4n** [comment]
yes, presumably this is making the fonts more closely match the designs or at least more consistent.  I'm slightly surprised on this one as I didn't think things were significantly broken (although I did implement them deliberately to slightly deviate from Trevor's design; shrinking them slightly to get a bit more content on the page) - would be useful to know what @stefanpearson has in mind here.

**Comment by stefanpearson** [comment]
At the time, I noticed the weights were off / wrong typeface etc., but turns out it was just Open Sans not loading in Safari. Although, there are deeper issues with the typography here (and ultimately the whole layout) with regards to the units being arbitrary all over the system. Although, I do appreciate some of these values may have come from the initial design assets. Ideally, there would be a proper baseline grid with a strict hierarchy as to make the typography and layout neater and more predictable. This is no trivial task, so we'll leave it for now 😄.

**Comment by ara4n** [comment]
Ah, phew, that makes a lot more sense (that it was the Safari bug).

Agreed that the arbitrary units is a bit of a disaster.  As per Monday 
I'll try to factor out some of the magic numbers from the CSS a bit, but 
totally agreed it'd be better to express things in terms of a grid 
layout.  (If the original designs had been grid-based we'd probably have 
done this from the outset).

I'll see what can be done to fix this on our side (with your advice), 
but don't want to block the current work on it.
