### ISSUE TITLE
Mention State Indicator Design Reworking

### ISSUE THREAD

**Issue by wmwragg** [vector-im/vector-web#1841]
- [x] Highlighting better sized
- [x] Badge tweaked to better match the design
- [x] Badge context menu indicator shows on hover on room name as well as badge area

Anything else?

**Comment by ara4n** [comment]
The other ambiguities we need to pin down are:

 * [] Whether to show the full width of the room name when no badge or context-menu-indicator is present (as per Trevor's original design).  We think this is important to avoid forcing undue truncation or wrapping of room names - we need to show as much info there as we can.
 * [] Whether to allow room names to wrap, and if so, at what granularity.  Trevor's design suggested truncation rather than wrapping.  If ribot's guidance is now that we should wrap rather than truncate, then I would prefer we preferred wrapping at word boundaries rather than on any character for best typography.  We then need a design for how to handle the vertical padding around wrapped roomtiles to avoid the aesthetics getting too cramped and busy.
* [] Whether the highlight should cover the whole width of the roomtile (including the badge & contextual menu indicator) when present.  (This may be the same as 'Highlighting better sized above'.

If you can discuss the options for the above with trevor and propose a solution such that we can sign-off on it would be much appreciated.

**Comment by antikewl** [comment]
I'll draw all this up, but, suggested solution:
- Instead of (another) ellipsis on the left panel (we already use an ellipsis for both the menus), we fade the text out to 0 alpha/bg colour for the last ~30px of the text. The room name does not wrap.
- We place the indicator on top of the (faded) text when/if it appears.
- We tooltip long room names on hover (much like we do on the minimised room panel view)
- Active room highlight covers the full width of the room name (incl. icon).

**Comment by ara4n** [comment]
this sounds good to me.  Only concerns are:

 * it will unnecessarily truncate the text when there are no overlays (badge or context selector).  Would it be possible for text to try to take up the whole available space (truncating as necessary), reducing in width only when the badge is displayed?
 * if the room highlight covers the full width of the room name, including icon, it's going to be huge, relative to the more modest ones in the current implementation which we quite like. Willing to see a proposal eitherway.

@wmwragg: looks like to avoid further confusion we should put this on hold until trevor has drawn it up so we can be 100% sure we're all on the same page and avoid further iteration.  Sorry again for the dead ends on this, and thanks for your patience.

**Comment by wmwragg** [comment]
Right you are, I'll let Trevor lead on this for now then

**Comment by ara4n** [comment]
One final implicit expectation that I should make explicit (as per chat a few mins ago) is that i'd expect selecting a room just to add the highlight - not to otherwise change the physical layout.  This is the behaviour on the current master branch (i.e. /beta). On /develop, the layout now pops for a given RoomTile when it's selected.
