### ISSUE TITLE
autocomplete doesn't work properly with non-ascii characters.

### ISSUE THREAD

**Issue by filterfish** [vector-im/vector-web#189]
I tried auto completing "tajĉjo" (who's currently in Matrix HQ) and it cycled through the 'J's but the autocompleted name was prefixed with "tajĉ". If I typed "tajĉjo:" the input box flashed red.

**Comment by ara4n** [comment]
I can't reproduce this in Matrix HQ - I typed ta<tab><tab><tab> and it correctly autocompletes to: "tajĉjo: ". What browser & OS is this?

**Comment by ara4n** [comment]
Alien reported this too with his エイリアン nick, which certainly reproduces the problem.

The issue seems to be a very strange assumption regarding the pattern matched for autocompleting names or nicks in https://github.com/vector-im/vector-web/blob/master/src/controllers/molecules/MessageComposer.js#L275 (and later on when doing the substitution).

@kegsay: any idea where this came from?

**Comment by filterfish** [comment]
I suspect this might not be relevant, however ...

I was just talking with one of our devs who was looking at some regular expressions and she noticed a difference between the \w and [:word:]. Now this was in ruby (ironically she was actually translating the code from python) but I wonder if python exhibits a similar behaviour.

ln fact I just tried the following:

```python
>>> import re
>>> 
>>> s = "tajĉjo"
>>> r = r"""\W"""
>>> re.split(r, s)
['taj', '', 'jo']
```
Of course I may have made some egregious newb mistake and it's completely irrelevant. If so please ignore!

**Comment by Kegsay** [comment]
@ara4n https://github.com/matrix-org/matrix-angular-sdk/blob/master/syweb/webclient/app/room/room-directive.js#L56
