### ISSUE TITLE
Linkify is broken in topic of #vector-feedback on dev, but not beta

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2010]
The linked URL never terminates on /develop

**Comment by ara4n** [comment]
Hopefully fixed by matrix-org/matrix-react-sdk@6786539 and 24152ff

**Comment by dbkr** [comment]
For the record, the full story here is that the topic of Riot (nee vector) user feedback contains no breaking space characters for some reason, and somewhere between 2.0.0-beta.4 and 2.1.0, linkify started treating non breaking space characters as part of the link. This happens anywhere with messages containing nonbreaking spaces and URLs (but is confused by the fact that if you c+p the topic from vector into the message box & hit send, it's fine, because it's sent as an html message)
