### ISSUE TITLE
Too many consecutive invisible events in the timeline crash the browser

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2020]
I have a private room which somehow gets stuck in an infinite loop of paginating backwards and then forwards and then backwards again until it crashes the browser.  I assume there's some kind of nasty event there.

**Comment by ara4n** [comment]
seeing this also in #matrix-dev in https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1472826679209650OlkoW:matrix.org

**Comment by ara4n** [comment]
The stack always looks like this:

```
enqueueUpdate  @   ReactUpdateQueue.js:25
enqueueSetState @   ReactUpdateQueue.js:210
ReactComponent.setState @   ReactComponent.js:64
(anonymous function)    @   TimelinePanel.js:272
_fulfilled  @   q.js:834
self.promiseDispatch.done   @   q.js:863
Promise.promise.promiseDispatch @   q.js:796
(anonymous function)    @   q.js:857
runSingle   @   q.js:137
flush   @   q.js:125
onNextTick  @   main.js:64
Item.run    @   browser.js:133
drainQueue  @   browser.js:103
```

Am wondering if onMessageListFillRequest in TimelinePanel's setState is somehow triggering onMessageListFillRequest and so tightlooping?

**Comment by WGH-** [comment]
Hi :)

**Comment by ara4n** [comment]
Rich's workaround in #438 is good enough in the short term.  In the longer term we need a proper fix so that invisible events of any kind don't nuke the world.

**Comment by ara4n** [comment]
@richvdh istr there was another possible mitigation for this; some heuristic to catch the looping back & forth. any idea what it was?

**Comment by Half-Shot** [comment]
[Permalink to my issue](https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$14756769592128GlQSw:half-shot.uk)

**Comment by richvdh** [comment]
The problem is that the event window is applied at a different level to where we decide which events to show, and indeed how much of the screen they take up.

The only real solution to this is to make the timelinewindow more flexible. Rather than having a fixed 250-event window, timelinewindow needs to unpaginate on demand from the TimelinePanel (and the TimelinePanel should pay attention to how much of the screen the events are taking up).

**Comment by aperezdc** [comment]
Using Epiphany here: I can confirm that the lockup happens also with WebKitGTK+. The `WebKitWebProcess` does not crash for the tab with Riot won't crash, but its CPU usage goes up 100% and stays there, with the tab being unusable. If it would be useful to have a WebKit stack trace to help solve this, just ping me and it wouldn't take me much time to provide one.

**Comment by lukebarnard1** [comment]
I've penned a solution already; following on from @richvdh's explanation above. Unpagination can be done on-demand by the TimelinePanel so long as it can calculate that the change in `scrollHeight` of `ScrollPanel` is less than p1 for forwards, p0 for backwards. See: 
![ima_b361281](https://cloud.githubusercontent.com/assets/6750344/20261572/43c780ae-aa56-11e6-96c7-53d11d34b7bd.jpeg)

So here, you could remove `e0` because it's invisible, `e1` and `e2` because neither of them take that much vertical space, but you could not remove `e3` because it is too large and would cause forward pagination. This would risk a loop occurring.

**Comment by lukebarnard1** [comment]
(See matrix-org/matrix-react-sdk#554 and matrix-org/matrix-react-sdk#553)
