### ISSUE TITLE
Big memory leak on Chrome according to davidar

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#217]
Could this just be because we're not reaping old events properly?

12:09 davidar
on the topic of vector, is there a memory leak, or does it just consume enormous amounts of memory?

davidar
like ~200MB almost immediately, over 500MB after a day or two

**Comment by ara4n** [comment]
This is being measured by chrome's Task Manager - not the JS heap.

**Comment by Kegsay** [comment]
That's useless then because plugins can contribute to that total. It's double useless because that value isn't the value after a clean GC (unlike heap snapshots which do a GC first).

We are not reaping events yet, but I do not believe this is a significant contributor to this. This was a different story on AngularJS because it was *swapping rooms* which made it leak every message in that room every time. This problem doesn't seem to exist in React.

**Comment by Kegsay** [comment]
Proposing to close or at least downgrade from p1.

**Comment by Kegsay** [comment]
Downgraded. If there is a heap snapshot which is indicating the outrageously large "200MB almost immediately" then bump it back up. I do not see this though.

**Comment by ara4n** [comment]
closing this as it's quite possible this is Chrome behaving as expected.  Evidence of actual leaks very welcome though :)
