### ISSUE TITLE
Megolm breaks when existing users join a room created by a new user which is already E2E

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2204]
This is best described by the screenshot below.  On the right we have the virginal @matthewtest31:matrix.org user.  On the left we have plain old matthew.

matthewtest31 created a room, and immediately turned on E2E and sent a message.  Then invited matthew, who joined.  matthewtest31 can see matthew's messages, but not vice versa - see the OLM_BAD_MESSAGE_MAC error on the LHS console.

Both clients are running the staging build (olm 1.2.0); i have reproduced this twice.

<img width="1920" alt="screen shot 2016-09-14 at 22 33 57" src="https://cloud.githubusercontent.com/assets/1294269/18531605/08809bb8-7acf-11e6-80d0-5e36ebe59212.png">

**Comment by NegativeMjark** [comment]
So the actual problem here is that we've run out of one-time keys on the server.
The clients need to upload new one-time keys semi regularly in order to avoid exhausting the list of one time keys, but currently I think we only do this when the page is loaded.

Separately there seems to be a bug that caused us to send an OLM message even though the destination had no valid one-time keys.

**Comment by NegativeMjark** [comment]
This can be reproduced on vector-e2f94c8722f2-react-2b9258d3779d-js-6e0b2de99f48 by repeatedly logging out, logging in and sending a message in one client while keeping another client open. Eventually the client that was left open will see OLM.BAD_MESSAGE_KEY_ID. If you keep an eye on the e2e_one_time_keys_json table in synapse, then you will see that this happens when the server runs out of one_time_keys for the receiving user.

**Comment by ara4n** [comment]
hopefully fixed by matrix-org/matrix-js-sdk#208.
