### ISSUE TITLE
€ key no worky

### ISSUE THREAD

**Issue by richvdh** [vector-im/vector-web#2561]
Mikaela says: For some reason I cannot type EUR symbol (AltGr + e) to Riot while I can type e.g. $ normally. EUR symbol also works on other applications and outside of Riot [and elsewhere in browser].

I am in Riot.im/app, this is Windows 10 and Firefox 50.0

Finnish Qwerty keyboard

**Comment by Mikaela** [comment]
I should probably also add that this Firefox is beta channel and this is on desktop PC at father where I am not so often (recovering for some time).

**Comment by Mikaela** [comment]
Issue reproduced without Rich Text Editor (that I had enabled), another information missing from this issue is that I am using the Stylish dark theme.

![2016-11-08 1](https://cloud.githubusercontent.com/assets/831184/20109355/5f3b7628-a5e8-11e6-9f15-a86ea7302af1.png)

The issue doesn't happen on other websites or Firefox address bar, but just in case.

**Comment by dbkr** [comment]
This is hitting the 'mute camera' shortcut (ctrl+e) because for reasons best known to microsoft, ev.ctrlKey is set when typing altgr+e.
