### ISSUE TITLE
Redesign members list

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#497]
* Move invite to bottom
* Show the first N members, with a "(...) 542 more" at bottom
* Put search bar on top (optional?)

**Comment by ara4n** [comment]
New plan: leave invite at top, but name it "Invite / Search".

**Comment by ara4n** [comment]
Also going to ensure that we literally show only one page of members, making room at the bottom for invited members to always be visible.

**Comment by Kegsay** [comment]
Related: https://github.com/vector-im/vector-web/issues/509

Braindumping from IRL:
 - Limit the number of `MemberTiles` and overflow the rest to a "and X more" tile.
 - If there are no invites pending, this list can occupy all the space it does currently.
 - If there ARE invites pending, this list should occupy ~80% and the invite section should be "sticky" at the bottom and occupy ~20%. We can programatically work this out because the `MemberTiles` have a constant height (so it becomes `Math.floor((heightAvailable * 0.8) / heightOfTile)` tiles)

**Comment by ara4n** [comment]
I experimented with making the invites section 'sticky' using flexbox, and whilst it's doable, it feels a bit weird to have so many different scrolling areas in the panel and non-integer cut-off EntityTiles between the joined & invited sections.  So I think the original plan as per the previous comment is probably still the best.

**Comment by Kegsay** [comment]
Now that we have "and X more" that concludes this bug afaik. Closing.
