### ISSUE TITLE
After an absolute /sync catchup, scrollback can fail to fill history

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#579]
There's a "49 unread messages" prompt, which is false, and the scrollback has failed to be backfilled.  JS console output attached.

<img width="1461" alt="screen shot 2016-01-01 at 23 05 51" src="https://cloud.githubusercontent.com/assets/1294269/12072570/c9f6430a-b0dc-11e5-8841-f38d38a84519.png">
[stuck-scrollback.txt](https://github.com/vector-im/vector-web/files/76066/stuck-scrollback.txt)

**Comment by richvdh** [comment]
To repro this, I think you need a room without many messages in to start with.

**Comment by richvdh** [comment]
The "49 unread messages" is #576.

**Comment by ara4n** [comment]
that room has weeks of scrollback however...

**Comment by richvdh** [comment]
Oh. Well, any tips for repro then?

Presumably this was on /beta, which is more-or-less react-sdk develop?

**Comment by ara4n** [comment]
yup, was /beta, which is develop as of xmas eve. no idea how to repro, 
other than possibly to leave the window scrolled back to an old offset, 
and then hibernate such that the next /sync is an absolute one?

**Comment by richvdh** [comment]
Tried that. I got a lot of warnings, but it sorted itself out. I'll investigate further.

**Comment by richvdh** [comment]
I'm struggling to figure out how this happened.

The console log shows that the problem started at 2016-01-01 20:09:05. At that point we got a sync batch (the first since the night before) which appears to have been 'limited' and therefore truncated the timeline in #torn. 

```
2016-01-01 20:08:19.456 MatrixChat.js:405 MatrixClient sync state => ERROR
2016-01-01 20:09:05.711 ScrollPanel.js:187 No node with scrollToken '$1451588616597955RvTXo:matrix.org'e.exports.r.createClass.scrollToToken @ ScrollPanel.js:187
...
2016-01-01 20:09:06.326 ScrollPanel.js:187 No node with scrollToken '$1451588616597955RvTXo:matrix.org'e.exports.r.createClass.scrollToToken @ ScrollPanel.js:187
2016-01-01 20:09:14.545 MatrixChat.js:405 MatrixClient sync state => SYNCING
2016-01-01 20:09:14.551 ScrollPanel.js:187 No node with scrollToken '$1451588616597955RvTXo:matrix.org'e.exports.r.createClass.scrollToToken @ ScrollPanel.js:187
2016-01-01 20:09:17.171 ScrollPanel.js:187 No node with scrollToken '$1451588616597955RvTXo:matrix.org'e.exports.r.createClass.scrollToToken @ ScrollPanel.js:187
```

(`$1451588616597955RvTXo:matrix.org` happened at 2015-12-31 19:03:36; there is at least a month of heavy traffic in this channel before this point.)

What I'd *expect* to happen at this point (and what happens whenever I try to repro it) is that the blanking of the timeline causes a scroll event to `scrollTop=0`, which in turn resets the saved scroll position, as well as triggering a pagination request. The fact that the scroll position wasn't reset suggests that the scroll event didn't happen, which in turn suggests that `scrollTop` was 0 to start with. But that would have triggered a pagination request, which should have either changed the scrollTop, or resulted in errors which would be visible in the console.

I'll keep thinking.

**Comment by richvdh** [comment]
I think this will probably go away (or at least be different) once matrix-org/matrix-react-sdk#70 lands, so in the absence of any idea how to repro this I'm going to ignore it for now.
