### ISSUE TITLE
this.refs.geminiPanel can sometimes return null and crash everything

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#589]
@richvdh: just got a nasty NPE due to

    _getScrollNode: function() {
        var panel = ReactDOM.findDOMNode(this.refs.geminiPanel);

returning null for panel
react sometimes seems to randomly fail to find its refs
which isn't handled very nicely at all.

This happened on randomly reloading an otherwise normal test room against a local HS.

**Comment by richvdh** [comment]
Hrm. It's not entirely obvious what to do about that. Don't suppose you got the rest of the stacktrace?

**Comment by Kegsay** [comment]
So it looks like `this.refs.scrollPanel` should always be defined at the points `_getScrollNode()` is called. However, @ara4n states that:

> returning null for the panel

Which indicates that `panel === null` rather than `this.refs.geminiPanel` being `null`. Managed to reproduce this if you call `_getScrollNode()` after `componentWillUnmount` (added a `setTimeout` to test it), which produces:

```
Uncaught TypeError: Cannot read property 'classList' of null
```

As for how this can happen normally, it looks like the race is here:

```javascript
_maybeFill: function(backwards) {
        [...]
        q.finally(fillPromise, () => {
            debuglog("ScrollPanel: "+dir+" fill complete");
            this._pendingFillRequests[dir] = false;
        }).then((hasMoreResults) => {
            if (hasMoreResults) {
                // further pagination requests have been disabled until now, so
                // it's time to check the fill state again in case the pagination
                // was insufficient.
                this.checkFillState();
            }
        }).done();
}
```

`checkFillState()` will call `_getScrollNode`. The promise is network-dependent and may resolve when the component is unmounted, resulting in the crash.

**Comment by richvdh** [comment]
heh; ironically I've just fixed the same bug in RoomView. Thanks kegan...

**Comment by ara4n** [comment]
I'm getting this at least 50% of the time on my dev box.  Full stacktrace is:

```
Uncaught TypeError: Cannot read property 'classList' of null_getScrollNode @ ScrollPanel.js:355
checkFillState @ ScrollPanel.js:161
(anonymous function) @ ScrollPanel.js:228
```

**Comment by richvdh** [comment]
oops, I forgot to make a PR for the fix to this

**Comment by ara4n** [comment]
@richvdh did this
