### ISSUE TITLE
Connectivity warning doesn't go away until you send or receive a message

### ISSUE THREAD

**Issue by dbkr** [vector-im/vector-web#606]

**Comment by Kegsay** [comment]
This seems to be a synapse bug. Repro steps:
 - Login to an account on a local HS.
 - `./synctl stop`
 - See the connectivity message appear.
 - `./synctl start`
 - Wait as it *never* returns anything from `/sync` until you receive a message.

When the JS SDK fails to get a `/sync` response it sets `timeout=1` instead of 30s in order to try to get some response *quickly* out of synapse when it regains connection. It seems this is now blocking indefinitely until the JS SDK client-side timeout kicks in at 2.5mins which then triggers another `/sync` which does the same thing (blocks forever rather than returning after 1ms). Synapse logs look very quiet during this period.

**Comment by Kegsay** [comment]
Filed as https://matrix.org/jira/browse/SYN-588

**Comment by Kegsay** [comment]
This can be worked around by using `timeout=0` rather than `timeout=1` in the JS SDK. Verified fix.
