### ISSUE TITLE
Switching rooms is ~2x slower on Jan 21 develop than Dec 23 develop

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#720]
Even after @kegsay's MemberList simplifications today, switching room is roughly 2-3x slower than on current /beta - this is doing a browser side-by-side comparison between the same rooms on my account.  This is a huge problem.

**Comment by ara4n** [comment]
it's 800ms to switch from Matrix Internal to Matrix HQ for me atm in Chrome, on 8-core MBP :(

**Comment by ara4n** [comment]
From a quick look, it seems that we're calling _viewRoom twice during a single switch, which seems very wrong.  Also, did the 50ms timeout for lazyloading members speed things up for more than the initial DOM render?

<img width="1470" alt="screen shot 2016-01-22 at 01 30 23" src="https://cloud.githubusercontent.com/assets/1294269/12500105/ec1c179a-c0a7-11e5-925a-1e6ec4b00d89.png">

**Comment by Kegsay** [comment]
Spent most of today profiling this. The conclusions were:
 - You can't accurately compare /beta and `develop` because /beta is run in `NODE_ENV=production`. We added in support to run `npm run start:prod`. With this, it turns out there is a ~60ms increase in room swapping time after making room avatar optimisations.
 - There's room for improvement across the board, though nothing else stands out as obviously wrong.

**Comment by ara4n** [comment]
* The multiple viewRooms invocation in my trace seems to be a profiler artefact
* Kegan tuned RoomAvatar which recovered most of the speed
* Truncated lists speed things up a bit too.
* However, there's still a major regression here unrelated to the stuff we fixed - possibly computing membership state required for inviting, or the overhead of the new abstractions we've added, or tinting, or something else.  Dropping priority as the overall performance is now level with where it was before

**Comment by richvdh** [comment]
we did a bunch of profiling and optimising; switching rooms is still slower than ideal but this bug isn't giving us much value any more.
