### ISSUE TITLE
Zero-signup access

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#81]
Ability to use the system without signing up for an account (creating an temporary anonymous placeholder account which can later be converted to a real account)

**Comment by ara4n** [comment]
This is getting more and more important. The biggest blocker is serverside - the registration mechanism to create a temporary user, and ACLs to force users to register before they are allowed to either join or post in a room.

**Comment by ara4n** [comment]
See https://matrix.org/jira/browse/SPEC-237 on the serverside.

**Comment by Kegsay** [comment]
This is a meaty task which can be broadly split into:
 - Development of the "registration bot" to guide you through the registration process.
 - Adding the UI for "guest access".
 - Modifying JS-SDK to add in guest-specific endpoints (specifically `room_id=` on `/events`).

**Comment by Kegsay** [comment]
Conclusion from RL discussion just now:
 - Guest login persisted to local storage
 - vector.im lands you in-app on the room directory
    * Rooms which cannot be r/w'd are marked on the list
    * Guests can click on rooms that are r or r/w to "peek" into it (live updates)
 - URIs to vector.im which specify a room ID land you in the room (if `world_readable`)
    * URI may need to include an event ID and server name to allow linking to messages that happened a long time ago. This needs to use the contextual messaging API.
 - Room view has a banner at the top (see designs 09_4) which:
    * Says 'this room is read-only' if it is read only. No join button. No text entry box.
    * Says 'you're viewing a preview of this room, join?' if it is r/w. Join button hits `/join`.
 - Room view's membership list has a big fat `< enter your name >` if you've been linked so anonymous users who can speak can have sensible names (think Etherpad).
 - There is a big Login button at the top-left of the window (above Favourites). This takes you to the registration page (current landing page).

Bot has been punted entirely because:
 - Opted to do it properly rather than fudge entirely client-side.
 - To do it properly requires an ephemeral data channel to exist between clients for things like password entry (this also would be handy for E2E key exchange, AS auth, etc).

**Comment by Kegsay** [comment]
This is blocked on Synapse implementing v2 `/sync` for guests, and the JS SDK implementing v2 `/sync`.

**Comment by Kegsay** [comment]
JS SDK now implements `/sync`, waiting on Synapse.

**Comment by Kegsay** [comment]
Synapse now implements it, so we should be good to go.

**Comment by Xe** [comment]
How do you use this?

**Comment by tobiasBora** [comment]
I managed to log as guest using the guest API: https://spec.matrix.org/v1.2/client-server-api/#guest-access

In the Javascript Matrix SDK client: https://matrix.org/sdks/#matrix-org-js-sdk I can log in browser using:

```
      const MATRIX_INSTANCE = "https://matrix.org"
      const tmpClient = window.matrixcs.createClient(MATRIX_INSTANCE);
      const { user_id, device_id, access_token } = tmpClient.registerGuest()
      const client = window.matrixcs.createClient({ baseUrl: MATRIX_INSTANCE,
                                                    accessToken: access_token,
                                                    userId: user_id,
                                                    deviceId: device_id})
      client.setGuest(true);
```

**Comment by m2acgi** [comment]
not work
