### ISSUE TITLE
we need a way to dismiss unsent messages prompt

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#891]
a cross shown when hovering?

**Comment by ara4n** [comment]
assigning to rich as he's been on an unsent message mission (and i don't want to collide with it)

**Comment by richvdh** [comment]
Would the intention be to leave the unsent messages (in red) in the timeline? (In contrast to what happens when you 'Cancel sending' on a message, which removes it from the timeline)

If so, things get slightly trickier semantically:
*  What happens when another message fails (so the prompt comes back) and the user clicks 'send all'? Do we resend all failed messages, or just the ones that happened since the user dismissed the prompt?
* What if the user changes room and comes back? Does the prompt reappear or stay hidden?

**Comment by richvdh** [comment]
@AmandineLP: those questions mostly for you, I guess

**Comment by richvdh** [comment]
* yes we should leave the messages
* when the prompt comes back and the user clicks it, we resend all failed messages
* when the user changes room, the prompt stays dismissed

**Comment by AmandineLP** [comment]
As discussed, let's just make the user choose between "resend all" and "remove all" and if they want to resend only part of the messages they send them individually and cancel all the others (or vice versa). It forces them to make a decision.

**Comment by richvdh** [comment]
Done by https://github.com/matrix-org/matrix-react-sdk/issues/238
