### ISSUE TITLE
After clicking on 'join' to join a room from a preview, the (v) 'jump to bottom' icon is displayed

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#943]
...despite you already being at the bottom of the room.

**Comment by richvdh** [comment]
Largely for my own reference, here's what's happening:

1. After the 'join' happens, we get a limited sync for the room which includes the last 10 events in the room's timeline. When we get a limited sync, we start a new EventTimeline, and use the previous sync token as a pagination token for the old timeline. Because we were peeking before, we already know about all 10 events, so we do not add any events to the new timeline.

2. Furthermore, the RoomView's TimelineWindow is still attached to the *old* timeline. This is now 'paginatable' (thus showing the (v) , but attempts to paginate it return no events. 

3. Once a new event arrives in the room, this is added (by /sync) to the new timeline. And next time we try to paginate the TimelineWindow, we get the new event, realise that we can join up the timelines, and normal service is restored.

Note that this issue is *intermittent* because sometimes we get our own 'join' event down the /sync pipe *after* the peek pipe, which means that step 3 effectively happens immediately after step 1.

Thoughts on potential fixes:
* spot that a limited sync includes events we already know about, so we don't actually need to reset the timeline
* reset the timelinewindow on join so that it looks at the new timeline rather than the old; we will then back-paginate from it and realise that we can join the timelines immediately.

**Comment by richvdh** [comment]
we probably need to reset the timelinewindow on gappy syncs anyway to fix #932.

**Comment by richvdh** [comment]
Well, now you not only get the (v) icon, you also get a blank roomview. Not necessarily an improvement.

**Comment by richvdh** [comment]
Meanwhile, this bug still exists in /beta, and what's worse is that if you click on the (v) icon, you sometimes get duplication of the last few items in the timeline.

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/issues/91
