### ISSUE TITLE
3PID invites don't contribute to a meaningful name for an unnamed room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#960]

**Comment by ara4n** [comment]
If I create an empty room and invite an unbound 3PID invite to it, then the room still stays "Unnamed room" rather than reflecting the fact it's a pending conversation with said person.

**Comment by ara4n** [comment]
This means:

a) keeping track of the uncensored 3PID invite details in the JS-SDK or even account_data
b) Modifying the js-sdk to return them as part of the room naming algorithm.

It really feels at times like this that 3PID invites are pretty ugly.  I wish that we'd made all invites 3PID-capable rather than bolting it on like this...

**Comment by AmandineLP** [comment]
Note that the same happen when the other party leaves a 1:1 room: room name becomes "Empty room" which in some way is true because you're alone in it, but it has data too so it isn't virgin.

Anyway, it's not a huge problem in my opinion for now, there are higher prioritise, but it has been bothering me so glad it's tracked somewhere. Let's also see what people think about it when using it. Maybe there are workarounds easier to implement to just differentiate these "invite acceptance pending" and "other party left" rooms from "Empty"... Can we just detect we are in these states and provide accurate names, without necessarily linking them to the invited/left person name?

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-js-sdk@8b887d8

**Comment by ara4n** [comment]
oops, missed the previous comment. split out into #985
